apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  releaseName: podinfo-release
  timeout: 10s
  chart:
    spec:
      chart: ./charts/podinfo
      sourceRef:
        kind: GitRepository
        name: podinfo
  valuesFrom:
    - kind: ConfigMap
      name: podinfo-values
